added-liquibase-part
jv-jul23-BandApart/booking-app pull request #7
Opened 2023-11-21 06:15 UTC by yevhenkukharchuk

2023-11-21 09:37 UTC, pavlov-n commented
Перевірив таску. Тобі треба: 
1. Стягнути мейн та подивитись як тепер виглядають моделі accomodation та amenities.(аменітіс як модельки немає, вона стрінгове поле у accomodation).
2. у всіх скриптах додати до varchar розмір, інакше воно не компілюється.
3. додати депенденсі у pom:  
 <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>

2023-11-21 09:38 UTC, pavlov-n requested changes

2023-11-21 09:38 UTC, pavlov-n commented on src/main/resources/db/changelog/changes/08-create-users-table.yml
> +                  constraints:
пропущено type:

2023-11-21 12:56 UTC, pavlov-n requested changes

2023-11-21 12:56 UTC, pavlov-n commented on src/main/resources/db/changelog/changes/01-create-accommodations-table.yml
> +                    unique: true
юнік тут більше не потрібен

2023-11-21 12:56 UTC, pavlov-n commented on src/main/resources/db/changelog/changes/04-create-bookings-table.yml
> +                    unique: true
тут також не потрібен

2023-11-22 08:38 UTC, anigilator479 approved these changes

2023-11-22 08:39 UTC, pavlov-n approved these changes

2023-11-22 08:40 UTC, merged